### ISSUE TITLE
Pop up bridge not working with Samsung Internet browser CustomTabs - V4.0.01

### ISSUE THREAD

**Issue by ankit1989** [braintree/popup-bridge-android#9]
### General information

* SDK/Library version: 0.1.1
* Android Version and Device: Samsung S7 with Android 6.0.1
* Samsung Internet Browser version : 4.0.01-81

### Issue description
Pop up bridge not working with Samsung Internet browser CustomTabs - Paypal payment (Sandbox) 

Steps:
1) Set Samsung Internet browser as default
2) Click on Check out with Paypal which opens Paypal payment sandbox url on Samsung Internet browser custom tabs
3) Click on Proceed with Sandbox purchase nothing happens
4) Same with Cancel Sandbox purchase

- From the More menu (on top right) click on "open in Internet" which open same page in full fledged Samsung Internet browser which all "Proceed with Sandbox purchase" & "Cancel Sandbox purchase" works.

- Tried sample app provided with this pop up bridge library on same Samsung Internet Browser and its not working as well.

- Tried on Samsung Internet Version 5.4.00-75 and it works fine.

**Comment by lkorth** [comment]
Thanks for the report @ankit1989. We also tested with 5.4.00-75 and it worked fine. It appears that there must have been a bug in 4.x with handling the return url schemes. 

Given that this has been fixed in recent versions of the browser and there isn't really any workarounds to fix it in older versions, I'll close this for now. If you do notice this behavior in any other browsers or versions, please comment on this issue and we'll follow up.
